language: java
jdk:
  - oraclejdk8
after_success:
  - ./gradlew pitest coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9a7812716d420b89cca
    on_success: always
    on_failure: always
    on_start: never