language: java
jdk:
  - oraclejdk8
after_success:
  - ./gradlew pitest coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9a7812716d420b89cca
    on_success: always
    on_failure: always
    on_start: never
  slack:
    secure: h5Rqkqb0nO8FLfHao0BVllJ0NVNvzrlSRtGfeDacLFyajC8k0GXgpACEAf5C7SzKeTKYz1bwYhFogaKYCJMxi9csH/NQfAJa+W70+d0aX6URMYozI6yi+a3EiIjFbAS7e4DxKFmnldEyqSVF6fECISS9uniJw0kiyJHKwB8TqJ02YpHkjquqXFPGNVYeLtJC7h++zCG2X+6x7vBllKVyV+9ObH6zp+/F8QK7k/v0VIskroqG48CPfnrdIGgZFiPNBA67M9xw32pXQzCSRvstmzrEualvPJHt7QRKAy2XE94WGpGCZJLjUo63BQJ0yfWcdUdnXL4BRLXh3M1M+SaceufscmXKxFRBClpEJZIfcBqDmj4kpQU9EcI445KwHjSwm4BDW4KisP9KB9KCxyj1DCR3rUeGbKxNguTmSXSU8q74c/CRTcW5XTGjHFEUTfFh23MYOEyrMO8zjV2LJN6/IsqfYJB4WDn2/1RQukHEtapetzV4t9/FBIEChVGgiAnnY096D7hf7swPoRtvsKBHJlWVp3qCu5NhDHOpOwpZyIg/vIfBDH6tpJMR6+ceZ/2KYnTOusUc926IdDz5x75oHfJvLi4sfknmAO+8VoXdhBZOlcoL4Gm6GMxNtcTWiwc80QmL8zoCAkHFw4D3lKIXc6wpYR1Ec3KsZw49rs51ee8=
